// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@lostgradient/editor/export/types` as a cinder sub-path.
export type {
  CommentsExportOptions,
  CommentsExportResult,
  CommentsJSONOptions,
  CommentsJSONResult,
  ExportedComment,
  ExportedSelection,
  ExportedThread,
  MarkdownSummaryOptions,
  MarkdownSummaryResult,
  UnifiedDiffOptions,
  UnifiedDiffResult,
} from '@lostgradient/editor/export/types';
