// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/diff` as a cinder sub-path.
export { computeLineDiff, computeWordChanges, getDiffStats, groupIntoHunks } from '@cinder/diff';
export type { DiffHunk, LineDiff, LineDiffStats, WordChange } from '@cinder/diff';
