// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/diff/types` as a cinder sub-path.
export type { DiffHunk, LineDiff, LineDiffStats, WordChange } from '@cinder/diff/types';
