// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/markdown/rendering/async` as a cinder sub-path.
export {
  initializeWorkerHighlighter,
  renderMarkdownAsync,
  terminateMarkdownWorker,
} from '@cinder/markdown/rendering/async';
export type { RenderOptions, RenderResult } from '@cinder/markdown/rendering/async';
