// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/markdown/rendering/highlighter` as a cinder sub-path.
export {
  BUNDLED_LANGUAGES,
  CSS_VARIABLE_THEME,
  PLAINTEXT_LANGUAGE,
  SUPPORTED_LANGUAGES,
  getHighlighter,
  getHighlighterSync,
  initializeHighlighter,
  isBundledLanguage,
  isLanguageSupported,
  resetHighlighter,
} from '@cinder/markdown/rendering/highlighter';
export type {
  BundledLanguage,
  Highlighter,
  PlaintextLanguage,
  SupportedLanguage,
  ThemeRegistration,
} from '@cinder/markdown/rendering/highlighter';
