// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/markdown/rendering/highlighter` as a cinder sub-path.
export * from '@cinder/markdown/rendering/highlighter';
