// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/markdown/rendering/mermaid-cache` as a cinder sub-path.
export {
  clearMermaidCache,
  getCacheKey,
  getCachedSvg,
  getMermaidCacheSize,
  setCachedSvg,
  withMermaidLock,
} from '@cinder/markdown/rendering/mermaid-cache';
