// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/markdown/rendering/types` as a cinder sub-path.
export type { CodeBlockInfo, RenderOptions, RenderResult } from '@cinder/markdown/rendering/types';
