import * as fixture from './check-token-contrast-test-fixtures.ts';

export type Lab = fixture.Lab;
export type OklchColor = fixture.OklchColor;
export type TokenArms = fixture.TokenArms;
export type TranslucentTokenArms = fixture.TranslucentTokenArms;

export const {
  AA_TEXT,
  NON_TEXT,
  accent,
  accentContrast,
  accentText,
  bg,
  border,
  borderFaint,
  borderInk,
  borderMuted,
  borderStrong,
  chartSeries,
  ciede2000,
  compositeOver,
  contrastRatio,
  css,
  cssPropertyToPath,
  danger,
  dangerActive,
  dangerBg,
  dangerBorder,
  dangerContrast,
  dangerFg,
  dangerHover,
  deriveFromAccent,
  deriveStatusTier,
  info,
  infoActive,
  infoBg,
  infoBorder,
  infoContrast,
  infoFg,
  infoHover,
  isInSrgbGamut,
  mixOklch,
  neutralBg,
  oklchToLinearSrgb,
  opacityDisabled,
  opacityFaint,
  opacityMuted,
  parseResolvedColor,
  polarityInk,
  readAllTokenValues,
  readNumberToken,
  readOklchToken,
  readResolvedValue,
  readTokenValue,
  readTranslucentToken,
  simulateCvd,
  success,
  successActive,
  successBg,
  successBorder,
  successContrast,
  successFg,
  successHover,
  surface,
  surfaceInset,
  surfaceRaised,
  text,
  toCieLab,
  translucentContrastOn,
  warning,
  warningActive,
  warningBg,
  warningBorder,
  warningContrast,
  warningFg,
  warningHover,
  wcagLuminance,
} = fixture;
