/**
 * Generates the typescript-consumer probe from the INSTALLED `@lostgradient/cinder/manifest`
 * (the packed tarball's manifest), so the probe covers EVERY published component
 * and its schema/variables artifacts — not a curated subset. Per-component export
 * breakage is the common failure mode, so the probe must be exhaustive and
 * regenerated on every run (the validator deletes `src/generated` first).
 *
 * Emits two files under `src/generated/`:
 *   - `probe.ts`     — imports the props type, default schema, and default
 *                      variables type for every component, and uses each at the
 *                      type level. Compiled by tsc under two condition sets.
 *   - `Probe.svelte` — imports every component value + its schema/variables and
 *                      references them, exercising the `svelte` condition through
 *                      svelte-check.
 *
 * Node baseline: 22+. JSON loaded via createRequire (no import attributes).
 */

import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const generatedDirectory = join(here, 'src', 'generated');

const manifest = require('@lostgradient/cinder/manifest');
if (!Array.isArray(manifest.components) || manifest.components.length === 0) {
  process.stderr.write('generate-probe: cinder/manifest has no components\n');
  process.exit(1);
}

// Fresh output every run — stale probes must never survive.
if (existsSync(generatedDirectory)) rmSync(generatedDirectory, { recursive: true, force: true });
mkdirSync(generatedDirectory, { recursive: true });

/** Convert a component id to a TypeScript-safe identifier segment. */
function toIdentifier(id) {
  return id
    .split(/[-/]/)
    .filter(Boolean)
    .map((segment) => segment[0].toUpperCase() + segment.slice(1))
    .join('');
}

// ---------------------------------------------------------------------------
// probe.ts — type-only surface, compiled under two condition sets:
//   Gate 1 (no `svelte` condition): resolves via the `types` condition — the
//           plain non-Svelte TS/NodeNext consumer lens.
//   Gate 2 (`customConditions: ["svelte"]`): when `types` is present it resolves
//           the same target as Gate 1 (TypeScript checks `types` first). The
//           gates DIVERGE only when a subpath has `svelte` but no `types`: Gate 1
//           fails (no condition matches) while Gate 2 falls back to the `.ts`
//           source via the `svelte` condition. Gate 2 therefore guards the
//           Svelte-aware consumer's type-resolution fallback, not a duplicate of
//           Gate 1. (Verified: drop `types`, keep `svelte` → Gate 1 TS2307, Gate 2 OK.)
// ---------------------------------------------------------------------------

const tsLines = [
  '// AUTO-GENERATED by generate-probe.mjs — do not edit. Covers every manifest',
  '// component: props type + default schema + default variables type.',
  '',
];

// `import type { X }` of a missing symbol is a TS2305 error even when X is
// never referenced, and `import type Default from 'sub'` of an unresolvable
// subpath is a TS2307/TS2305 error too. So merely importing the props type,
// the default schema type, and the default variables type for every component
// forces tsc to resolve the main export's and both metadata subpaths' `types`
// conditions. We deliberately do NOT instantiate the props type — several
// components ship generic props (e.g. `DataListProps<T>`), and the contract we
// are proving is "the type name resolves from the subpath", not "it takes zero
// type arguments".
const tsBodyLines = [];
for (const component of manifest.components) {
  const ident = toIdentifier(component.id);
  const propsType = `${component.exportName}Props`;
  // Props type — resolves via the component main export's `types` condition.
  tsLines.push(`import type { ${propsType} as ${ident}Props } from '${component.import}';`);
  // Default schema type — resolves via the schema subpath's `types` condition.
  tsLines.push(`import type ${ident}Schema from '${component.import}/schema';`);
  // Default variables type — resolves via the variables subpath's `types`.
  tsLines.push(`import type ${ident}Variables from '${component.import}/variables';`);

  // Reference the schema + variables defaults at the type level (they are not
  // generic, so a typeof query is safe and additionally proves the imported
  // type is usable, not merely declared).
  tsBodyLines.push(`declare const ${ident}SchemaProbe: typeof ${ident}Schema;`);
  tsBodyLines.push(`declare const ${ident}VariablesProbe: typeof ${ident}Variables;`);
  tsBodyLines.push(`void ${ident}SchemaProbe;`);
  tsBodyLines.push(`void ${ident}VariablesProbe;`);
  // The `import type { Props as Alias }` above already errors (TS2305) if the
  // props type name does not resolve from the component subpath, even though we
  // never reference the alias — that is the contract we are proving. We do not
  // instantiate it because several props types are generic.
}

tsLines.push('');
tsLines.push(...tsBodyLines);
tsLines.push('');
writeFileSync(join(generatedDirectory, 'probe.ts'), tsLines.join('\n'));

// ---------------------------------------------------------------------------
// Probe.svelte — value surface under the svelte condition (Gate 3).
// Imports each component's default value and its schema/variables defaults, and
// references them so svelte-check must resolve every subpath via `svelte`.
// ---------------------------------------------------------------------------

const svelteImports = [];
const svelteRefs = [];
for (const component of manifest.components) {
  const ident = toIdentifier(component.id);
  svelteImports.push(`  import ${ident} from '${component.import}';`);
  svelteImports.push(`  import ${ident}SchemaValue from '${component.import}/schema';`);
  svelteImports.push(`  import ${ident}VariablesValue from '${component.import}/variables';`);
  svelteRefs.push(`  void ${ident};`);
  svelteRefs.push(`  void ${ident}SchemaValue;`);
  svelteRefs.push(`  void ${ident}VariablesValue;`);
}

const svelteLines = [
  '<!-- AUTO-GENERATED by generate-probe.mjs — do not edit. -->',
  '<script lang="ts">',
  ...svelteImports,
  '',
  ...svelteRefs,
  '</script>',
  '',
  '<!-- Probe references components at the value level so svelte-check resolves',
  '     every subpath through the `svelte` export condition. -->',
  '',
];
writeFileSync(join(generatedDirectory, 'Probe.svelte'), svelteLines.join('\n'));

process.stdout.write(
  `generate-probe: emitted probe.ts + Probe.svelte for ${manifest.components.length} components\n`,
);
