// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/commentary/anchor-decorations` as a cinder sub-path.
export * from '@cinder/commentary/anchor-decorations';
