// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@lostgradient/editor/anchoring` as a cinder sub-path.
export {
  buildAnchorFromSelection,
  detectBlockLevelAnchor,
  generateBlockId,
} from '@lostgradient/editor/anchoring';
