// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/commentary/anchoring` as a cinder sub-path.
export {
  buildAnchorFromSelection,
  detectBlockLevelAnchor,
  generateBlockId,
} from '@cinder/commentary/anchoring';
