// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/commentary/anchor-decorations` as a cinder sub-path.
export { anchorPluginKey, createAnchorPlugin } from '@cinder/commentary/anchor-decorations';
export type {
  AnchorPluginOptions,
  AnchorPluginState,
  AnchorState,
} from '@cinder/commentary/anchor-decorations';
