// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/markdown/templates/sanitize-html` as a cinder sub-path.
export { sanitizeHtml } from '@cinder/markdown/templates/sanitize-html';
export type { SanitizeHtmlOptions } from '@cinder/markdown/templates/sanitize-html';
