// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/editor/sanitize-html` as a cinder sub-path.
export { sanitizeHtml } from '@cinder/editor/sanitize-html';
export type { SanitizeHtmlOptions } from '@cinder/editor/sanitize-html';
