// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@lostgradient/markdown/templates/sanitize-html` as a cinder sub-path.
export { sanitizeHtml } from '@lostgradient/markdown/templates/sanitize-html';
export type { SanitizeHtmlOptions } from '@lostgradient/markdown/templates/sanitize-html';
