// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@lostgradient/markdown/templates/template-render` as a cinder sub-path.
export { renderTemplate } from '@lostgradient/markdown/templates/template-render';
