// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/markdown/templates/template-render` as a cinder sub-path.
export { renderTemplate } from '@cinder/markdown/templates/template-render';
