// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/editor/template-render` as a cinder sub-path.
export * from '@cinder/editor/template-render';
