// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@lostgradient/markdown/templates/template-placeholders` as a cinder sub-path.
export {
  buildPlaceholderCandidatesFromJsonSchema,
  isBlockedSegment,
  parsePlaceholderTokens,
  renderTemplate,
  resolveTemplatePlaceholders,
  validatePlaceholderTokens,
} from '@lostgradient/markdown/templates/template-placeholders';
