// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@lostgradient/editor/editor/test-utilities` as a cinder sub-path.
export {
  createDocFromMarkdown,
  debugDocStructure,
} from '@lostgradient/editor/editor/test-utilities';
export type { TestDocument } from '@lostgradient/editor/editor/test-utilities';
