// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/commentary/editor/test-utilities` as a cinder sub-path.
export { createDocFromMarkdown, debugDocStructure } from '@cinder/commentary/editor/test-utilities';
export type { TestDocument } from '@cinder/commentary/editor/test-utilities';
