/**
 * Regression test for `04-schema-hygiene-a`: fifteen components declared
 * their props as a bare intersection with an HTML attribute type
 * (`HTMLAttributes<...> & { class?: string }`) instead of the house
 * `Omit<Base, 'class'> & { class?: string }` pattern, so the schema
 * generator saw `class` as `ClassValue & string`, couldn't reduce it, and
 * emitted it under `metadata.unsupportedProps` with `reason: 'unknown-shape'`.
 *
 * This test enumerates every generated `<name>.schema.ts` file as TEXT (not
 * via a computed/glob module import — this repo's unmodellable-imports guard
 * rejects those, and only the FULL suite surfaces the failure) and asserts
 * none of them list `class` under `unsupportedProps`.
 */

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, test } from 'bun:test';

const COMPONENTS_DIR = join(import.meta.dir, 'components');

const EXCLUDED_COMPONENTS = new Set<string>();

function findSchemaFiles(): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(COMPONENTS_DIR)) {
    // Underscore-prefixed directories (e.g. `_radio`) are private/internal
    // components deliberately excluded from `discoverComponentDirectories()`
    // and therefore never regenerated by `components:generate` — mirror that
    // exclusion here so this test only checks schemas the generator owns.
    if (entry.startsWith('_')) continue;
    if (EXCLUDED_COMPONENTS.has(entry)) continue;

    const directory = join(COMPONENTS_DIR, entry);
    if (!statSync(directory).isDirectory()) continue;

    const schemaFile = join(directory, `${entry}.schema.ts`);
    try {
      if (statSync(schemaFile).isFile()) files.push(schemaFile);
    } catch {
      continue; // no schema.ts for this directory — skip.
    }
  }
  return files.toSorted();
}

describe('generated component schemas — class prop narrowing', () => {
  test('no schema lists `class` under unsupportedProps', () => {
    const offenders: string[] = [];

    for (const schemaFile of findSchemaFiles()) {
      const source = readFileSync(schemaFile, 'utf8');
      if (/name:\s*'class'/.test(source)) {
        offenders.push(schemaFile.slice(COMPONENTS_DIR.length + 1));
      }
    }

    expect(offenders).toEqual([]);
  });
});
