// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@lostgradient/editor/shared/anchor-types` as a cinder sub-path.
export type {
  AnchorStatus,
  AnchorType,
  CommentAnchor,
  PersistedAnchor,
  RuntimeAnchor,
  TextQuoteAnchor,
} from '@lostgradient/editor/shared/anchor-types';
