import type { IconProps } from 'lucide-svelte';
import type { ComponentType, SvelteComponent } from 'svelte';
export { default as ArrowUp } from 'lucide-svelte/icons/arrow-up';
export { default as Bold } from 'lucide-svelte/icons/bold';
export { default as Brain } from 'lucide-svelte/icons/brain';
export { default as Check } from 'lucide-svelte/icons/check';
export { default as CheckCheck } from 'lucide-svelte/icons/check-check';
export { default as ChevronDown } from 'lucide-svelte/icons/chevron-down';
export { default as ChevronLeft } from 'lucide-svelte/icons/chevron-left';
export { default as ChevronRight } from 'lucide-svelte/icons/chevron-right';
export { default as ChevronUp } from 'lucide-svelte/icons/chevron-up';
export { default as CircleAlert } from 'lucide-svelte/icons/circle-alert';
export { default as CircleDot } from 'lucide-svelte/icons/circle-dot';
export { default as Code } from 'lucide-svelte/icons/code';
export { default as Copy } from 'lucide-svelte/icons/copy';
export { default as FileCode } from 'lucide-svelte/icons/file-code';
export { default as FileText } from 'lucide-svelte/icons/file-text';
export { default as FolderGit2 } from 'lucide-svelte/icons/folder-git-2';
export { default as GitBranch } from 'lucide-svelte/icons/git-branch';
export { default as Globe } from 'lucide-svelte/icons/globe';
export { default as Heading1 } from 'lucide-svelte/icons/heading-1';
export { default as Heading2 } from 'lucide-svelte/icons/heading-2';
export { default as Heading3 } from 'lucide-svelte/icons/heading-3';
export { default as Italic } from 'lucide-svelte/icons/italic';
export { default as LinkIcon } from 'lucide-svelte/icons/link';
export { default as List } from 'lucide-svelte/icons/list';
export { default as ListOrdered } from 'lucide-svelte/icons/list-ordered';
export { default as Maximize2 } from 'lucide-svelte/icons/maximize-2';
export { default as MessageCircle } from 'lucide-svelte/icons/message-circle';
export { default as MessageSquare } from 'lucide-svelte/icons/message-square';
export { default as MoreHorizontal } from 'lucide-svelte/icons/more-horizontal';
export { default as Paperclip } from 'lucide-svelte/icons/paperclip';
export { default as Pencil } from 'lucide-svelte/icons/pencil';
export { default as Pilcrow } from 'lucide-svelte/icons/pilcrow';
export { default as Plus } from 'lucide-svelte/icons/plus';
export { default as Quote } from 'lucide-svelte/icons/quote';
export { default as Redo2 } from 'lucide-svelte/icons/redo-2';
export { default as RefreshCw } from 'lucide-svelte/icons/refresh-cw';
export { default as RotateCcw } from 'lucide-svelte/icons/rotate-ccw';
export { default as Search } from 'lucide-svelte/icons/search';
export { default as Square } from 'lucide-svelte/icons/square';
export { default as Strikethrough } from 'lucide-svelte/icons/strikethrough';
export { default as Terminal } from 'lucide-svelte/icons/terminal';
export { default as Trash2 } from 'lucide-svelte/icons/trash-2';
export { default as Undo2 } from 'lucide-svelte/icons/undo-2';
export { default as Unlink } from 'lucide-svelte/icons/unlink';
export { default as X } from 'lucide-svelte/icons/x';

export type { IconProps } from 'lucide-svelte';

export type IconComponent = ComponentType<SvelteComponent<IconProps>>;
