import type { DocSection } from './docs-sections.ts';

export const COLOR_DOC_SECTIONS: readonly DocSection[] = ([] = [
  {
    slug: 'accent',
    headings: ['## Accent'],
    cssProperties: [
      '--cinder-accent-solid',
      '--cinder-accent-contrast',
      '--cinder-accent-text',
      '--cinder-accent-text-hover',
      '--cinder-accent-solid-hover',
      '--cinder-accent-solid-active',
      '--cinder-accent-solid-active-on-fill',
    ],
  },
  {
    slug: 'status-solid',
    headings: ['## Status — solid'],
    cssProperties: [
      '--cinder-status-info-solid',
      '--cinder-status-success-solid',
      '--cinder-status-warning-solid',
      '--cinder-status-danger-solid',
      '--cinder-status-danger-contrast',
      '--cinder-status-danger-solid-hover',
      '--cinder-status-danger-solid-active',
      '--cinder-status-info-solid-hover',
      '--cinder-status-info-solid-active',
      '--cinder-status-success-solid-hover',
      '--cinder-status-success-solid-active',
      '--cinder-status-warning-solid-hover',
      '--cinder-status-warning-solid-active',
      '--cinder-status-success-contrast',
      '--cinder-status-warning-contrast',
      '--cinder-status-info-contrast',
      '--cinder-severity-critical',
      '--cinder-severity-critical-background',
    ],
  },
  {
    slug: 'status-semantic-triples',
    headings: ['## Status — semantic triples'],
    cssProperties: [
      '--cinder-status-info-background',
      '--cinder-status-info-text',
      '--cinder-status-info-border',
      '--cinder-status-success-background',
      '--cinder-status-success-text',
      '--cinder-status-success-border',
      '--cinder-status-warning-background',
      '--cinder-status-warning-text',
      '--cinder-status-warning-border',
      '--cinder-status-danger-background',
      '--cinder-status-danger-text',
      '--cinder-status-danger-border',
      '--cinder-status-neutral-background',
      '--cinder-status-neutral-text',
      '--cinder-status-neutral-border',
      '--cinder-accent-background',
      // `--cinder-accent-text` is documented in the Accent section. The soft
      // family's foreground was a pure alias of it and folded into it during the
      // CIN-33 rename, so it is no longer a separate token to list here.
      '--cinder-accent-border',
      '--cinder-status-info-muted',
      '--cinder-status-info-subtle',
      '--cinder-status-success-muted',
      '--cinder-status-success-subtle',
      '--cinder-status-warning-muted',
      '--cinder-status-warning-subtle',
      '--cinder-status-danger-muted',
      '--cinder-status-danger-subtle',
    ],
  },
  {
    slug: 'transparency-checkerboard',
    headings: ['## Transparency checkerboard'],
    cssProperties: ['--cinder-checker-base', '--cinder-checker-tile'],
  },
  {
    slug: 'chart-series',
    headings: ['## Chart series'],
    cssProperties: [
      '--cinder-chart-series-1',
      '--cinder-chart-series-2',
      '--cinder-chart-series-3',
      '--cinder-chart-series-4',
      '--cinder-chart-series-5',
      '--cinder-chart-series-6',
      '--cinder-chart-series-7',
      '--cinder-chart-series-8',
    ],
  },
]);
