import type { DocSection } from './docs-sections.ts';

export const FOUNDATION_DOC_SECTIONS: readonly DocSection[] = ([] = [
  {
    slug: 'spacing',
    headings: ['## Spacing'],
    cssProperties: [
      '--cinder-space-0',
      '--cinder-space-0-5',
      '--cinder-space-1',
      '--cinder-space-1-5',
      '--cinder-space-2',
      '--cinder-space-2-5',
      '--cinder-space-3',
      '--cinder-space-3-5',
      '--cinder-space-4',
      '--cinder-space-5',
      '--cinder-space-6',
      '--cinder-space-7',
      '--cinder-space-8',
      '--cinder-space-10',
      '--cinder-space-12',
      '--cinder-space-16',
      '--cinder-space-20',
      '--cinder-space-24',
      '--cinder-space-32',
    ],
  },
  {
    slug: 'radii-and-shadows',
    headings: ['## Radii and shadows'],
    cssProperties: [
      '--cinder-radius-sm',
      '--cinder-radius-md',
      '--cinder-radius-lg',
      '--cinder-radius-full',
      '--cinder-shadow-sm',
      '--cinder-shadow-md',
      '--cinder-shadow-lg',
      '--cinder-shadow-overlay',
    ],
  },
  {
    slug: 'control-heights',
    headings: ['## Control heights'],
    cssProperties: [
      '--cinder-control-height-xs',
      '--cinder-control-height-sm',
      '--cinder-control-height-lg',
    ],
  },
  {
    slug: 'typography',
    headings: ['## Typography'],
    cssProperties: [
      '--cinder-font-sans',
      '--cinder-font-mono',
      '--cinder-text-2xs',
      '--cinder-text-xs',
      '--cinder-text-sm',
      '--cinder-text-base',
      '--cinder-text-md',
      '--cinder-text-lg',
      '--cinder-text-xl',
      '--cinder-text-2xl',
      '--cinder-text-3xl',
      '--cinder-text-4xl',
      '--cinder-text-5xl',
      '--cinder-leading-none',
      '--cinder-leading-tight',
      '--cinder-leading-snug',
      '--cinder-leading-normal',
      '--cinder-leading-relaxed',
      '--cinder-tracking-tight',
      '--cinder-tracking-normal',
      '--cinder-tracking-wide',
      '--cinder-font-normal',
      '--cinder-font-medium',
      '--cinder-font-semibold',
      '--cinder-font-bold',
      '--cinder-type-tab-size',
      '--cinder-touch-target-min',
    ],
  },
  {
    slug: 'layout',
    headings: ['## Layout'],
    cssProperties: [
      '--cinder-content-width',
      '--cinder-content-width-prose',
      '--cinder-content-width-narrow',
      '--cinder-content-width-wide',
    ],
  },
  {
    slug: 'motion',
    headings: ['## Motion'],
    cssProperties: [
      '--cinder-duration-instant',
      '--cinder-duration-fast',
      '--cinder-duration-base',
      '--cinder-duration-normal',
      '--cinder-duration-moderate',
      '--cinder-duration-slow',
      '--cinder-duration-spin',
      '--cinder-duration-pulse',
      '--cinder-duration-progress-bar-indeterminate',
      '--cinder-duration-progress-ring-spin',
      '--cinder-ease-standard',
      '--cinder-ease-decelerate',
      '--cinder-ease-accelerate',
      '--cinder-ease-spring',
      '--cinder-ease-in-out',
    ],
  },
  {
    slug: 'surfaces',
    headings: ['## Surfaces'],
    cssProperties: [
      '--cinder-surface-canvas',
      '--cinder-surface',
      '--cinder-surface-raised',
      '--cinder-surface-inset',
      '--cinder-surface-hover',
      '--cinder-surface-pressed',
      '--cinder-surface-raised-hover',
      '--cinder-surface-raised-pressed',
      '--cinder-surface-upcoming-marker',
      '--cinder-surface-inverse',
      '--cinder-text-inverse',
      '--cinder-border-inverse',
      '--cinder-polarity-ink',
    ],
  },
  {
    slug: 'text-colors',
    headings: ['## Text colors'],
    cssProperties: [
      '--cinder-text-default',
      '--cinder-text-muted',
      '--cinder-text-subtle',
      '--cinder-text-disabled',
      '--cinder-fill-disabled',
      '--cinder-terminal-ansi-black',
      '--cinder-terminal-ansi-red',
      '--cinder-terminal-ansi-green',
      '--cinder-terminal-ansi-yellow',
      '--cinder-terminal-ansi-blue',
      '--cinder-terminal-ansi-magenta',
      '--cinder-terminal-ansi-cyan',
      '--cinder-terminal-ansi-white',
      '--cinder-terminal-ansi-bright-black',
      '--cinder-terminal-ansi-bright-red',
      '--cinder-terminal-ansi-bright-green',
      '--cinder-terminal-ansi-bright-yellow',
      '--cinder-terminal-ansi-bright-blue',
      '--cinder-terminal-ansi-bright-magenta',
      '--cinder-terminal-ansi-bright-cyan',
      '--cinder-terminal-ansi-bright-white',
    ],
  },
  {
    slug: 'borders',
    headings: ['## Borders'],
    cssProperties: [
      '--cinder-border-ink',
      '--cinder-border',
      '--cinder-border-faint',
      '--cinder-border-muted',
      '--cinder-border-strong',
      '--cinder-toggle-track-off-resting',
      '--cinder-toggle-track-off-hover-resting',
    ],
  },
  {
    slug: 'opacity',
    headings: ['## Opacity'],
    cssProperties: [
      '--cinder-opacity-disabled',
      '--cinder-opacity-muted',
      '--cinder-opacity-faint',
    ],
  },
  {
    slug: 'semantic-aliases',
    headings: ['## Semantic aliases'],
    cssProperties: [
      '--cinder-pad-control',
      '--cinder-pad-card',
      '--cinder-gap-stack',
      '--cinder-gap-inline',
      '--cinder-radius-control',
      '--cinder-radius-surface',
    ],
  },
  {
    slug: 'focus-ring',
    headings: ['## Focus ring'],
    cssProperties: [
      '--cinder-ring-width',
      '--cinder-ring-offset',
      '--cinder-ring-offset-color',
      '--cinder-ring-color',
      '--cinder-ring-on-accent',
    ],
  },
  {
    slug: 'z-index-layers',
    headings: ['## Z-index layers'],
    cssProperties: [
      '--cinder-z-tooltip',
      '--cinder-z-dropdown',
      '--cinder-z-popover',
      '--cinder-z-backdrop',
      '--cinder-z-modal',
      '--cinder-z-toast',
      '--cinder-z-focused-affordance',
      '--cinder-z-drag-preview',
    ],
  },
  {
    slug: 'overlay-surfaces',
    headings: ['## Overlay surfaces'],
    cssProperties: [
      '--cinder-overlay-backdrop',
      '--cinder-overlay-blur',
      '--cinder-overlay-padding',
      '--cinder-overlay-radius',
    ],
  },
  {
    slug: 'scrollbars',
    headings: ['## Scrollbars'],
    cssProperties: [
      '--cinder-scrollbar-size',
      '--cinder-scrollbar-track',
      '--cinder-scrollbar-thumb',
      '--cinder-scrollbar-thumb-hover',
    ],
  },
]);
