/**
 * Generates a reviewable inventory of Cinder's authored CSS token surface.
 *
 * This is intentionally a one-way discovery artifact: the DTCG corpus added
 * by later stages becomes the source of truth. Keeping the inventory generator
 * lets `--check` prove that the migration began from a complete, current view
 * of the legacy CSS rather than an incomplete hand-picked token list.
 */

import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { AtRule, parse, Rule, type Container, type Node } from 'postcss';
import { format } from 'prettier';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDirectory, '..', '..');
const tokensBasePath = join(packageRoot, 'src', 'styles', 'tokens-base.css');
const inventoryPath = join(packageRoot, 'src', 'tokens', 'token-inventory.md');

type TokenInventoryEntry = {
  cssProperty: string;
  proposedPath: string;
  section: string;
  source: 'default' | 'reduced-motion' | 'forced-reduced-motion';
  value: string;
  aliases: readonly string[];
  needsCssRecipe: boolean;
};

function normalizeSection(comment: string): string | undefined {
  const heading = comment
    .split('\n')
    .map((line) => line.replaceAll(/^[\s*=*-]+|[\s*=*-]+$/g, ''))
    .find((line) => /^[A-Z][A-Z /&-]+$/.test(line));
  return heading
    ?.toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-')
    .replaceAll(/^-|-$/g, '');
}

function tokenPath(cssProperty: string): string {
  return cssProperty.slice('--cinder-'.length).split('-').join('.');
}

function aliases(value: string): readonly string[] {
  return [...value.matchAll(/var\(\s*(--cinder-[a-z0-9-]+)/gi)]
    .map((match) => match[1])
    .filter((name): name is string => name !== undefined)
    .toSorted();
}

function needsCssRecipe(value: string): boolean {
  return /\b(?:color-mix|light-dark)\(|\boklch\(\s*from\b/i.test(value);
}

function collectDeclarations(
  container: Container,
  source: TokenInventoryEntry['source'],
  entries: TokenInventoryEntry[],
): void {
  let section = 'unclassified';

  for (const node of container.nodes ?? []) {
    if (node.type === 'comment') {
      section = normalizeSection(node.text) ?? section;
      continue;
    }
    if (node.type !== 'decl' || !node.prop.startsWith('--cinder-')) continue;

    entries.push({
      cssProperty: node.prop,
      proposedPath: tokenPath(node.prop),
      section,
      source,
      value: node.value,
      aliases: aliases(node.value),
      needsCssRecipe: needsCssRecipe(node.value),
    });
  }
}

function findTopLevelRoot(nodes: readonly Node[]): Container {
  const rootRule = nodes.find(
    (node): node is Rule => node instanceof Rule && node.selector.startsWith(':root'),
  );
  if (!rootRule) {
    throw new Error('Could not find the top-level :root token block.');
  }
  return rootRule;
}

function findReducedMotionRoot(nodes: readonly Node[]): Container {
  const media = nodes.find(
    (node): node is AtRule =>
      node instanceof AtRule &&
      node.name === 'media' &&
      node.params.includes('prefers-reduced-motion: reduce'),
  );
  if (!media) {
    throw new Error('Could not find the reduced-motion media block.');
  }
  return findTopLevelRoot(media.nodes ?? []);
}

function findForcedReducedMotionRoot(nodes: readonly Node[]): Container {
  const rootRule = nodes.find(
    (node): node is Rule =>
      node instanceof Rule && node.selector.startsWith(":root[data-reduced-motion='on']"),
  );
  if (!rootRule) throw new Error('Could not find the forced reduced-motion token block.');
  return rootRule;
}

export function inventoryFromCss(source: string): readonly TokenInventoryEntry[] {
  const root = parse(source, { from: tokensBasePath });
  const entries: TokenInventoryEntry[] = [];
  collectDeclarations(findTopLevelRoot(root.nodes), 'default', entries);
  collectDeclarations(findReducedMotionRoot(root.nodes), 'reduced-motion', entries);
  collectDeclarations(findForcedReducedMotionRoot(root.nodes), 'forced-reduced-motion', entries);
  return entries.toSorted((left, right) => left.cssProperty.localeCompare(right.cssProperty));
}

export function renderInventory(entries: readonly TokenInventoryEntry[]): string {
  const lines = [
    '# Cinder token inventory',
    '',
    '> Generated by `bun run --filter=@lostgradient/cinder tokens:inventory`. Do not edit by hand.',
    '',
    '| CSS property | Proposed DTCG path | Section | Source | Aliases | CSS recipe | Authored value |',
    '| --- | --- | --- | --- | --- | --- | --- |',
  ];

  for (const entry of entries) {
    lines.push(
      `| \`${entry.cssProperty}\` | \`${entry.proposedPath}\` | ${entry.section} | ${entry.source} | ${entry.aliases.map((alias) => `\`${alias}\``).join(', ') || '—'} | ${entry.needsCssRecipe ? 'yes' : 'no'} | \`${entry.value.replaceAll('|', '\\|')}\` |`,
    );
  }

  return `${lines.join('\n')}\n`;
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const source = await readFile(tokensBasePath, 'utf8');
  const output = await format(renderInventory(inventoryFromCss(source)), { parser: 'markdown' });
  const existing = await Bun.file(inventoryPath)
    .text()
    .catch(() => '');

  if (check) {
    if (existing !== output) {
      throw new Error(
        `Token inventory drifted. Run bun run --filter=@lostgradient/cinder tokens:inventory.`,
      );
    }
    return;
  }

  await Bun.write(inventoryPath, output);
}

if (import.meta.main) await main();
