// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@lostgradient/editor/comments/types` as a cinder sub-path.
export {
  ANCHOR_CONTEXT_LENGTH,
  createDocumentAnchor,
  createTextQuoteAnchor,
  generateId,
  isDocumentAnchor,
  isTextAnchor,
  timestamp,
} from '@lostgradient/editor/comments/types';
export type {
  AnchorStatus,
  AnchorType,
  AnchorUpdate,
  Comment,
  CommentAnchor,
  CommentCreateEvent,
  CommentDeleteEvent,
  CommentUpdateEvent,
  CreateCommentInput,
  CreateThreadInput,
  PersistedAnchor,
  PersistedReviewSession,
  PersistedThread,
  ReanchorResult,
  ReviewState,
  RuntimeAnchor,
  TextQuoteAnchor,
  Thread,
  ThreadCreateEvent,
  ThreadDeleteEvent,
  UpdateCommentInput,
} from '@lostgradient/editor/comments/types';
