// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/commentary/comments/types` as a cinder sub-path.
export * from '@cinder/commentary/comments/types';
