// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@lostgradient/markdown/diff/line-diff` as a cinder sub-path.
export {
  computeLineDiff,
  computeWordChanges,
  getDiffStats,
  groupIntoHunks,
} from '@lostgradient/markdown/diff/line-diff';
export type {
  DiffHunk,
  LineDiff,
  LineDiffStats,
  WordChange,
} from '@lostgradient/markdown/diff/line-diff';
