// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@lostgradient/markdown/diff/types` as a cinder sub-path.
export type {
  Change,
  ChangeGroup,
  ChangeType,
  DiffMeta,
  DiffResult,
  DiffStats,
  PositionEntry,
  SourcePosition,
  TextRange,
  ViewMode,
} from '@lostgradient/markdown/diff/types';
