// Generated by scripts/generate-exports.ts — do not edit by hand.
// Re-exports the public surface of `@cinder/markdown/diff/types` as a cinder sub-path.
export * from '@cinder/markdown/diff/types';
